export const SET_TRANSLATE_TO = 'SET_TRANSLATE_TO';
export const TRANSLATE_TEXT = 'TRANSLATE_TEXT';
export const TRANSLATE_TEXT_SUCCESS = 'EXTRACT_TEXT_SUCCESS';
export const TRANSLATE_TEXT_ERROR = 'EXTRACT_TEXT_ERROR';
export const SET_SHOW_BOX = "SET_SHOW_BOX";
export const SAVE_E_TEXT = 'SAVE_E_TEXT';