export const EXTRACT_TEXT = 'EXTRACT_TEXT';
export const EXTRACT_TEXT_SUCCESS = 'EXTRACT_TEXT_SUCCESS';
export const EXTRACT_TEXT_ERROR = 'EXTRACT_TEXT_ERROR';
export const RESET_LOADING_TEXT = 'RESET_LOADING_TEXT';
