export const TRANSLATE_IMAGE = 'TRANSLATE_IMAGE';
export const TRANSLATE_TEXT_SUCCESS = 'TRANSLATE_TEXT_SUCCESS';
export const TRANSLATE_TEXT_ERROR = 'TRANSLATE_TEXT_ERROR'
export const RESET_LOADING_TEXT = 'RESET_LOADING_TEXT'